### ISSUE TITLE
true is not a postcss plugin error with 7.0.0

### ISSUE THREAD

**Issue by dsebastien** [postcss/postcss-mixins#109]
Is this error known?
How should I load postcss-mixins with v7.0.0?

**Comment by ai** [comment]
Yeap. It is an error because PostCSS 7 does not support PostCSS 8 plugins.

BTW, in latest PostCSS 7.0.x release we fixed the error message to clear `Update PostCSS or downgrade plugin`. SO I am closing this issue.
