### ISSUE TITLE
Conflict with simple-vars

### ISSUE THREAD

**Issue by sporto** [postcss/postcss-mixins#111]
Trying to upgrade to 7.0.1 we are seeing this issue (using webpack).

Given you have a mixin like:

```
@define-mixin border-1 $color {
	border: 1px solid $color;
}
```

If we have a postcss config with only `postcss-mixins`

```
module.exports = {
  plugins: [
    require('postcss-mixins')
  ]
}
```

The webpack bundle compiles fine.

But if we add `postcss-simple-vars`:

```
module.exports = {
  plugins: [
    require('postcss-mixins'),
    require('postcss-simple-vars')(...)
  ]
}
```

We get this:

```
(1:1) postcss-simple-vars: /home/sebastian/Source/sporto/postcss-mixins-repro/app.css Undefined variable $color

> 1 | @define-mixin border-1 $color {
    | ^
  2 |   border: 1px solid $color;
  3 | }
````

**Comment by ai** [comment]
Sorry, I am burned out after PostCSS 8 release.

Will return to PostCSS a little later.

**Comment by jfroffice** [comment]
I have the same issue on `v6.2.3`

**Comment by greenyas** [comment]
For me it is working on v6.2.3. Config is the following 
module.exports = {
  plugins: [
    require('postcss-import'),
    require('postcss-mixins')
    require('postcss-simple-vars')
    require('postcss-nested')(...)
  ]
}

**Comment by sporto** [comment]
I made a repo reproducing the issue https://github.com/sporto/repro-postcss-mixin

**Comment by ai** [comment]
Fixed https://github.com/postcss/postcss-simple-vars/commit/a674a56e49a5d4a93db9c09a10ff76da2768a493

**Comment by ai** [comment]
The fix was released in `postcss-simple-vars` 6.0.2

**Comment by sporto** [comment]
@ai thanks

**Comment by cullylarson** [comment]
FYI, https://github.com/postcss/postcss-simple-vars/commit/a674a56e49a5d4a93db9c09a10ff76da2768a493 creates a new problem. If you have variables (not mixin parameters) inside a `@define-mixin`, they will no longer be replaced by postcss-simple-vars. C.f. https://github.com/postcss/postcss-simple-vars/issues/92
