### ISSUE TITLE
Mixins not being compiled

### ISSUE THREAD

**Issue by lhguerra** [postcss/postcss-mixins#120]
My code:
```
@define-mixin nice-mixin {
  border: 3px solid red;
  color: black;
}

.test {
  @mixin nice-mixin;
  color: yellow;
}
```
My config (using postcss.config.js):
```
module.exports = {
  plugins: [
    require("postcss-easy-import"),
    require("postcss-mixins"),
    require("precss"),
    require("autoprefixer")
  ]
};
```
My scripts and packages:
```
"scripts": {
    "styles": "rm -f ./dist/main.css && postcss ./styles/main.css -o ./dist/main.css --verbose",
    "styles:watch": "yarn styles -w"
  },
  "devDependencies": {
    "postcss": "^8.2.6",
    "postcss-cli": "^8.3.1",
    "postcss-easy-import": "^3.0.0",
    "postcss-mixins": "^7.0.3",
    "precss": "^4.0.0"
  },
```
My output:
```
.test {
  color: yellow;
}
```

I'm not seeing what I'm doing different from the docs and I also get no error or warning in the terminal while running the styles command.

**Comment by ai** [comment]
`precss` has built-in mixins. We may have a conflict.

**Comment by lhguerra** [comment]
Good catch! The precss page has no info about mixins, so I didn't consider :/

Disabling it makes mixins work, so I'll reopen the issue there.

**Comment by Alexufo** [comment]
@lhguerra precss  already dead plugin. Did you replace it for something else?

**Comment by lhguerra** [comment]
For the project I was working on, I actually ended up using sass from `@csstools/postcss-sass`
