### ISSUE TITLE
Fallback properties

### ISSUE THREAD

**Issue by Antonio-Laguna** [postcss/postcss-mixins#121]
Hi here!

I've been using this awesome plugin for a while and today I got to wonder how to set up a fallback. Imagine a simple mixin that uses properties that are not in all browsers and I want to provide a fallback.

```js
module.exports = function (rule) {
  const styles = {};

  styles['font-size'] = '16px';
  styles['font-size'] = 'clamp(...)';

  return styles;
};
```

Given that `clamp` is not available on old browsers, how could I make sure that both values are passed?

**Comment by ai** [comment]
Will it work as you expected?

```
styles['font-size'] = ['16px', 'clamp()']
```

**Comment by Antonio-Laguna** [comment]
Works like a charm! Thanks! Sorry if this was a dumb question but I couldn't find it mentioned anywhere.

**Comment by ai** [comment]
Nope. The problem is lack of docs for mixins API :)
