### ISSUE TITLE
importing mixins from a file

### ISSUE THREAD

**Issue by Alexufo** [postcss/postcss-mixins#127]
style.scss

@import '../../node_modules/normalize.css/normalize';
@import '_vars.scss';
@import '_mixin.pcss';
@import '_main.scss';

Mixins from _mixin are not visible.  I get error `Undefined mixin`

But then I past mixins code into style.scss they become work

      gulp.task('postcss', function () {
          var plugins = [
              postcssimport(),
              postcssmixins(),
              postcssnested(),
              rfs(rfs_options),
              postcsssimplevars(),
          ];
      
          return gulp.src("./src/css/style.scss")
              .pipe(postcss(plugins, {
                  parser: postcssscss
              }))
              .pipe(gulp.dest('./public_html_src/'));
      });

**Comment by ai** [comment]
It is Sass way. PostCSS way is to pass option with mixin directory to `postcss-mixins` https://github.com/postcss/postcss-mixins#options
