### ISSUE TITLE
Mixin processing issue

### ISSUE THREAD

**Issue by AndreyLuzinov** [postcss/postcss-mixins#132]
I wrote a following mixin in my mixins.pcss:

`@define-mixin buttonInsetFocusShadow {
  &::not([disabled]) {
    &::focus {
      box-shadow: inset var(--focus-shadow);
    }
  }
}`

And I've used it like this:
`.button {
   ...
  @mixin buttonInsetFocusShadow;
`

I got 
![image](https://user-images.githubusercontent.com/8442311/121049026-023afa80-c7c0-11eb-98d5-c2c528af5b11.png)

So it looks like my mixin hasn't been processed by post-css engine and just inserted as is in css file.

My plugin config:
![image](https://user-images.githubusercontent.com/8442311/121051494-2dbee480-c7c2-11eb-9caf-8bd4cbd0b572.png)

What I'm doing wrong?

**Comment by ai** [comment]
Check `postcss-nested` issues. It is known issue, but nobody send PR yet.

**Comment by AndreyLuzinov** [comment]
Thanks for quick response
