### ISSUE TITLE
Vars inside rules names doesn't work

### ISSUE THREAD

**Issue by Alexufo** [postcss/postcss-mixins#134]
I want to replace 120dpi to var but I cant find how to do it. Vars or concatenation ` @media (min-resolution: ${num}dpi)` doesn't work. 

      require('postcss-mixins')({
          mixins: {
              image: function (mixin, path) {
                  return {
                      '&': {
                          background: 'url(' + path + ')'
                      },
                      '@media (min-resolution: 120dpi)': {
                          '&': {
                              background: 'url(' + path + '@2x)'
                          }
                      }
                  }
              }
          }
      });

**Comment by ai** [comment]
```diff
- '@media (min-resolution: 120dpi)': {
+ '@media (min-resolution: ' + num + ')': {
```

**Comment by Alexufo** [comment]
@ai thanks but I got SyntaxError: Unexpected token '+'
I use it inside vitejs.

This is my postcss.config.js

```js
module.exports = {

  map: false,
  plugins: {
    'postcss-mixins': {

      mixins: {
        image: function (mixin, path) {
          return {
            path: {
              background: 'url(' + path + ')'
            },
            '@media (min-resolution: 120dpi)': {
              '&': {
                background: 'url(' + path + '@2x)'
              }
            }
          }
        }
      }

    },
    'postcss-nested': {},
    'postcss-nesting': {}
  }
}

```
Var `path` render as string. It becomes to:

```css
#app path {
  background: url("100");
}
...

```

**Comment by ai** [comment]
Sorry, I can't help you with general JS questions.

Try to debug the code by `console.log(returnObject)` (don't forget to save object to this variable).

**Comment by Alexufo** [comment]
Thanks. Maybe I don't provide clean info.
this is mixin   `@mixin image "test" `
```js
module.exports = {

  map: false,
  plugins: {
    'postcss-mixins': {

      mixins: {
        image: function (mixin, path) {
          return {
            path: {
              background: 'url(' + path + ')'
            } 
          }
        }
      }

    },
    'postcss-nested': {},
    'postcss-nesting': {}
  }
}
```


This is returned object: 
```js
transforming (1) index.html{
  path: { background: 'url("test")' },
  '@media (min-resolution: 120dpi)': { '&': { background: 'url("test"@2x)' } }
}
```
Please look at path. path = "test" It does not become as  'test ' like in property of background  'url("test"@2x)'. 

I cant understand how to use variables in keys. [Your solution](https://github.com/postcss/postcss-mixins/issues/134#issuecomment-886161634) with concatenation doesn't work.

**Comment by ai** [comment]
Check what is inside `path` variable. Seems like it has `"test"`. Just use JS to remove `"`. For instance, by `path.slice(1, -1)`.

**Comment by Alexufo** [comment]
Got it.
Iinstead
> ```diff
> - '@media (min-resolution: 120dpi)': {
> + '@media (min-resolution: ' + num + ')': {
> ```

Must be in [] if we want to calculate name of property in object.

```diff
-  '@media (min-resolution: 120dpi)': {
+  ['@media (min-resolution: ' + num + ')']: {
```
