### ISSUE TITLE
Possible typo in Readme?

### ISSUE THREAD

**Issue by mdizo** [postcss/postcss-mixins#148]
https://github.com/postcss/postcss-mixins/blob/882168dd754683a03d17f1c69a6033e81befe9d9/README.md?plain=1#L221

Maybe you meant `@mixin-content`?

**Comment by ai** [comment]
Thanks. Fixed https://github.com/postcss/postcss-mixins/commit/cd8e9f791f7410f9eb06042f5df3808936dfd6cd
