### ISSUE TITLE
Can I create `mixin functions` in their own files and import them?

### ISSUE THREAD

**Issue by ItzaMi** [postcss/postcss-mixins#150]
I have a folder named `mixins` and inside of it I'm defining my CSS files with `@define-mixin`.
However, I want to have a conditional in one of my mixins; I read about [Function mixins](https://github.com/postcss/postcss-mixins#function-mixin) and saw that you could directly state. functions inside the `config` file.
But I would like to create these custom `mixins` in the same place as others.
So I have a `interactions.ts` inside `mixins` with the following:

```ts
function focusAppearance(arg: string | undefined) {
	if (!arg) {
        return {
			'box-shadow': 'var(--box-shadow-accent-0px-spread)',
			'@media (hover: hover)': {
				'&:hover': { 'box-shadow': 'var(--box-shadow-accent-4px-spread)' }
			}
		};
    }
    
    return [... some other stuff]
}

export { focusAppearance}
```

How can I now use this `focusAppearance`? Is that even possible?

**Comment by ai** [comment]
Can you show the PostCSS config and the `mixins/` dir content?
