### ISSUE TITLE
Annoying squiggly lines under properly defined and working mixins in VS Code 

### ISSUE THREAD

**Issue by Maryanos** [postcss/postcss-mixins#154]
Hi, I've just moved from Sass to PostCss and I'm having an annoying problem with mixins that are working correctly but are marked by VS code as an error with annoying squiggly lines. 
You  can see how they are defined and used on screenshots below, this leads of course to more underlined properties even if all is correctly working. 
Also package.json included below. 
Is there any help I can get from you guys to make my life bright again? 

![Screenshot_18](https://user-images.githubusercontent.com/51508760/219856797-5ad13b99-5a41-4ef4-b70b-e18902e4c60f.jpg)
![Screenshot_17](https://user-images.githubusercontent.com/51508760/219856798-4a34bf1b-f4ba-4d98-86c0-85658a3d6ec2.jpg)
![Screenshot_19](https://user-images.githubusercontent.com/51508760/219856869-5d8f017b-518a-4e79-9b43-dc72b86bf47b.jpg)

**Comment by ai** [comment]
You need to ask VS Code team
