### ISSUE TITLE
Request mixinDirGlobs instead or in addition to mixinsDir

### ISSUE THREAD

**Issue by jedmao** [postcss/postcss-mixins#16]
How would you feel about introducing a `mixinsDirGlobs` option of some kind? I'm trying to filter-out my specs, which are also in my mixins folder, where my mixin is named `foo.js` and its spec is named `foo.spec.js`.

https://github.com/postcss/postcss-mixins/blob/54aed1530fb68b2c8680fe4a47f4542de9cb7523/index.js#L150

If nothing else, I'd like some way to filter-out these `*.spec.js` files. If it were a glob, I could do `*!(.spec).js`.

**Comment by ai** [comment]
Lets name it `mixinsFiles`. I am wait for PR :).

**Comment by jedmao** [comment]
OK!
