### ISSUE TITLE
problems with image paths in mixins

### ISSUE THREAD

**Issue by muhandis86** [postcss/postcss-mixins#160]
I updated the postsss-mixin dependency from version 6.2.0 to 9.0.4, after which the compilation of background paths in mixins occurs incorrectly, i.e. in url. What happens is that where the $(image) variable is expanded in mixins, after the first parenthesis is encountered, a quote is placed before the closing parenthesis, so the path is not fully resolved.

![111](https://github.com/postcss/postcss-mixins/assets/91059335/af741f0f-eb26-45af-bfc4-22e89056a83e)

package.json and _mixin.css:

![222](https://github.com/postcss/postcss-mixins/assets/91059335/0a697e3f-1af8-4af0-b199-beba590b21e6)

**Comment by muhandis86** [comment]
with postcss-mixins 6.2.0 lworks without problems

**Comment by ai** [comment]
The problem was with `postcss-cachebuster` which was not updated to PostCSS 8
