### ISSUE TITLE
PostCss mixin not process correctly in react+vite project

### ISSUE THREAD

**Issue by mohdmujahithali** [postcss/postcss-mixins#172]
i am using the vite + react app

### 1) installed all the below pacakges
npm install postcss-nested postcss-mixins postcss-simple-vars postcss-import --save-dev

### 2) updated the postcss.config.js with the postcss plugins
export default {
  plugins: {
    'postcss-import': {},
    'postcss-mixins': {},
    'postcss-simple-vars': {},
    'postcss-nested': {},
    tailwindcss: {},
    autoprefixer: {},
  },
};

### 3) created a Mixin in CSS (font-faces.css)
@define-mixin fontFace $fontName, $folderName, $fileName, $fontWeight, $fontStyle {
  @font-face {
    font-family: $(fontName);
    src:
      url('../fonts/$(folderName)/$(fileName).woff2') format('woff2'),
      url('../fonts/$(folderName)/$(fileName).woff') format('woff');
    font-weight: $(fontWeight);
    font-style: $(fontStyle);
    font-display: swap;
  }
}

@define-mixin gothamFontFace $fileName, $fontWeight, $fontStyle: normal {
  @mixin fontFace Gotham, gotham, $(fileName), $(fontWeight), $(fontStyle);
}

@define-mixin openSansFontFace $fileName, $fontWeight, $fontStyle: normal {
  @mixin fontFace 'Open Sans', open-sans, $(fileName), $(fontWeight), $(fontStyle);
}

@layer base {
  /* Gotham fonts */
  @mixin gothamFontFace Gotham-Black, 900;
  @mixin gothamFontFace Gotham-BlackItalic, 900, italic;
  @mixin gothamFontFace Gotham-Bold, 700;
  @mixin gothamFontFace Gotham-BoldItalic, 700, italic;
  @mixin gothamFontFace Gotham-Medium, 500;
  @mixin gothamFontFace Gotham-MediumItalic, 500, italic;
  @mixin gothamFontFace Gotham-Book, 400;
  @mixin gothamFontFace Gotham-BookItalic, 400, italic;
  @mixin gothamFontFace Gotham-Light, 300;
  @mixin gothamFontFace Gotham-LightItalic, 300, italic;
  @mixin gothamFontFace Gotham-XLight, 200;
  @mixin gothamFontFace Gotham-XLightItalic, 200, italic;
  @mixin gothamFontFace Gotham-Thin, 100;
  @mixin gothamFontFace Gotham-ThinItalic, 100, italic;

  /* Open Sans fonts */
  @mixin openSansFontFace OpenSans-ExtraBold, 900;
  @mixin openSansFontFace OpenSans-ExtraBoldItalic, 900, italic;
  @mixin openSansFontFace OpenSans-Bold, 700;
  @mixin openSansFontFace OpenSans-BoldItalic, 700, italic;
  @mixin openSansFontFace OpenSans-SemiBold, 600;
  @mixin openSansFontFace OpenSans-SemiBoldItalic, 600, italic;
  @mixin openSansFontFace OpenSans-Medium, 500;
  @mixin openSansFontFace OpenSans-MediumItalic, 500, italic;
  @mixin openSansFontFace OpenSans-Regular, 400;
  @mixin openSansFontFace OpenSans-RegularItalic, 400, italic;
  @mixin openSansFontFace OpenSans-Light, 300;
  @mixin openSansFontFace OpenSans-LightItalic, 300, italic;
}

## Issue
After build, font-faces is not processed in dist/style.css

@charset "UTF-8";@define-mixin fontFace $fontName,$folderName,$fileName,$fontWeight,$fontStyle{@font-face {font-family: $(fontName); src: url("../fonts/$(folderName)/$(fileName).woff2") format("woff2"),url("../fonts/$(folderName)/$(fileName).woff") format("woff"); font-weight: $(fontWeight); font-style: $(fontStyle); font-display: swap;}}@define-mixin gothamFontFace $fileName,$fontWeight,$fontStyle: normal{@mixin fontFace Gotham,gotham,$(fileName),$(fontWeight),$(fontStyle);}@define-mixin openSansFontFace $fileName,$fontWeight,$fontStyle: normal{@mixin fontFace "Open Sans",open-sans,$(fileName),$(fontWeight),$(fontStyle);}*,

also, getting warning while build

../fonts/$(folderName)/$(fileName).woff2 referenced in ../fonts/$(folderName)/$(fileName).woff2 didn't resolve at build 
time, it will remain unchanged to be resolved at runtime                                                                time, it will remain unchanged to be resolved

../fonts/$(folderName)/$(fileName).woff referenced in ../fonts/$(folderName)/$(fileName).woff didn't resolve at build time, it will remain unchanged to be resolved at runtime

**Comment by ai** [comment]
I can't accept so big input/output examples as issue. Open source is community and you need to do very big part of your work.

1. Create new small project
2. Try to reproduce an issue with minimum code

If it is not like this, it is commercial support.

P. S. I have similar code and it works, so very likely that it is something bad with environment, plugins versions, etc. Environment questions is also commercial support.
