### ISSUE TITLE
Importing mixins?

### ISSUE THREAD

**Issue by jeron-diovis** [postcss/postcss-mixins#21]
Did I understand correctly that mixins works only in the file where they are defined?

I'm using postcss with webpack. Have two css files. One contains mixin definition, in second one it's used. On build got this:

```
Undefined mixin myMixin
.test {
  @mixin myMixin;
  ^
}

ERROR in ./src/layouts/contact/styles.css
Module build failed: TypeError: Cannot call method 'toString' of undefined
    at new Input (/Users/jeron_diovis/dev/projects/MediaSapiens/react-boilerplate/node_modules/css-loader/node_modules/postcss/lib/input.js:29:24)
    at Object.parse [as default] (/Users/jeron_diovis/dev/projects/MediaSapiens/react-boilerplate/node_modules/css-loader/node_modules/postcss/lib/parse.js:17:17)
    at new LazyResult (/Users/jeron_diovis/dev/projects/MediaSapiens/react-boilerplate/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:54:42)
    at Processor.process (/Users/jeron_diovis/dev/projects/MediaSapiens/react-boilerplate/node_modules/css-loader/node_modules/postcss/lib/processor.js:30:16)
    at processCss (/Users/jeron_diovis/dev/projects/MediaSapiens/react-boilerplate/node_modules/css-loader/lib/processCss.js:170:24)
    at Object.module.exports (/Users/jeron_diovis/dev/projects/MediaSapiens/react-boilerplate/node_modules/css-loader/lib/loader.js:21:15)
 @ ./src/layouts/contact/component.js 27:17-40
```

To make mixin visible globally I must define it in JS, in `mixins` option?

**Comment by ai** [comment]
There is two way:

1.  Merge CSS files before PostCSS. It will be too complicated in webpack.
2. Use JS mixins in `mixins` options.

I have plan to allow global CSS mixins. If you ant them, please create a issue.

**Comment by ai** [comment]
There is also third way to import CSS with mixin by `postcss-import` before running `postcss-mixins`. But this way is too hacky.

**Comment by jeron-diovis** [comment]
Ok, so it seems that postcss isn't what I need. 
Probably using good old preprocessors will be much more simple and reliable.
Thanks for so quick response.

**Comment by ai** [comment]
@jeron-diovis yeap, mixins is not main goal of PostCSS. It is only addition task to make build process easier without other tool. Use Sass and PostCSS for task, that are impossible on Sass.

But, BTW, how you will fix this task in Sass? If you will concat CSS in webpack after Sass complication, you will still have same issue. If you will use `@import` it will be same hacky way as `postcss-import`.

**Comment by jeron-diovis** [comment]
Well... it's reasonable.
I'm totally confused. Playing with this for several hours already, and what - for now there is no simple way to make things like mixins reusable (without overhead of code duplication) with webpack's modular approach, except of defining them in JS via postcss-mixins?

**Comment by ai** [comment]
@jeron-diovis there is `mixins` option specially for cross-file reusabling :) Ben Frain even write good article about it http://benfrain.com/creating-and-referencing-javascript-mixins-and-variables-with-postcss/

**Comment by ai** [comment]
@jeron-diovis try `postcss-import` (but look at hot-reload preset in [`postcss-loader` docs](https://github.com/postcss/postcss-loader#integration-with-postcss-import)) and use Sass way:

```js
postcss: [
    require('postcss-import'),
    require('postcss-mixins')
]
```

```css
@import "../lib/mixins/size";

.icon {
    @mixin size 15px;
}
```

**Comment by ai** [comment]
I open issue there to fix it in better than Sass way: https://github.com/postcss/postcss-mixins/issues/22

But it will not be ready soon.

**Comment by jeron-diovis** [comment]
@ai, already read that article, thanks. 
There was an ideal dream that we can write, you know, css in css :), and webpack will somehow provide cross-file reusabling with it's magic. 
But world is cruel, as always)

I already tried `postcss-import`. It works, but it just includes content of imported file, so if I need same mixin in another file, it will be copied again and again. Sure we can put each mixin in it's own file, so there will be not so much duplicated code - but still don't think it's a very good.

**Comment by ai** [comment]
@jeron-diovis what is problem with coping mixin in files? It is exactly how Sass `@import` works :).

**Comment by jeron-diovis** [comment]
You're right.
Just, in Sass we usually do this once somewhere in main file. As then everything else is imported there too, we have an effect "import once, use everywhere". And no duplication)

Ok, now I understand, where I was wrong in my desires. Great thanks you for responses. I think I'll try to play with js-mixins. Maybe team will like it, who knows :)

**Comment by ai** [comment]
@jeron-diovis if you are familiar ith JS, you can send PR with CSS common mixins. PostCSS plugins are very easy (just a simple JS functions transforming CSS node’s tree).

**Comment by jeron-diovis** [comment]
I am, but not very well imagine what and how should be transformed to provide this functionality. In other words, it will take some time to learn how this all works. Right now don't have this time.

**Comment by jeron-diovis** [comment]
I have another question.
Is it possible to safely use postcss together with css-modules? As for now, defining `composes` statement which references another file, seems to just disable any postcss in that file. Let say it looks like this:

```css
/* styles1.css */
.someClass { ... }
@define-mixin myMixin { ... }
```

```css
/* styles2.css */
.anotherClass {
    composes: someClass from "styles1.css"
}
```
With this, in my build I see content of styles1.css as-is, with `@define-mixin`. After removing `composes` it compiles as it should. Didn't tried another postcss features with this yet, don't know whether they will fail too, but - is this normal?

**Comment by ai** [comment]
CSS Modules is PostCSS based project. It is just few libraries and custom PostCSS plugins. So you can add PostCSS plugins directly to CSS Modules copiler and have 100 % support.

**Comment by jeron-diovis** [comment]
As I understand, this is what I need:
https://www.npmjs.com/package/css-modules-loader-core
And with webpack, it will be then:
```js
module: {
    loaders: [
      {
        test: /\.css$/,
        loader: "css!postcss",
      }
    ]
  },

  postcss: [ core ]
```

Smth like that?

**Comment by ai** [comment]
@jeron-diovis nope, CSS Modules requires few libraries for ebpack integration. So they can’t work just from PostCSS.

I read a docs and didn’t find how to set PostCSS plugins to webpack CSS Modules (seems like I miss it with broserify CSS Modules plugin).

@markdalgleish can we add PostCSS plugins to CSS Modules in webpack?
