### ISSUE TITLE
Support comments in function mixins

### ISSUE THREAD

**Issue by jedmao** [postcss/postcss-mixins#27]
Would you merge a PR that added support for comments in [function mixins](https://github.com/postcss/postcss-mixins#function-mixin), similar to [these lines](https://github.com/postcss/postcss-mixins/blob/bdef2e3dcd650293a9a2c50f123e29ba57778f85/index.js#L17-L21)?

Unfortunately, I can't think of a better way than this:

```js
export default function() {
  return {
    '// postcss-font-pack: ignore-next': {},
    font: '0/0 serif'
  };
}
```

Open to better suggestions.

**Comment by ai** [comment]
Why we need comments?

**Comment by jedmao** [comment]
For the very reason that some plugins (e.g., [`postcss-font-pack`](https://github.com/jedmao/postcss-font-pack#ignoring-sections), [`postcss-bem-linter`](https://github.com/postcss/postcss-bem-linter#ignoring-specific-selectors)) use comments to ignore certain selectors or declarations.

**Comment by ai** [comment]
@jedmao why you close it?

**Comment by jedmao** [comment]
I was able to achieve this with `mixin.cloneBefore({ type: 'comment', text: 'foo' })`. It does make things a bit dirty though, which is why I submitted https://github.com/postcss/postcss-mixins/pull/29 just now, which will suit my needs better (global css mixins).
