### ISSUE TITLE
Possible to allow nested syntax in mixin definitions (withou separate install of postcss-nested)?

### ISSUE THREAD

**Issue by davidtheclark** [postcss/postcss-mixins#3]
A mixin definition is the only place that I want to allow nested syntax --- and that is because the limitations of at-rule mixin definitions mean I *need* to use nesting if I want to target pseudo-elements and pseudo-classes. Right now, to use nested syntax I need to run `postcss-mixins` and then run `postcss-nested`. This means that people on my team could actually use nested syntax wherever they want. Do you think it would be possible for the mixins plugin to parse nested syntax internally so that I could nest within definitions and otherwise not run my css through the `postcss-nested` plugin?

**Comment by ai** [comment]
I understand your point and agree, that it will be useful in some cases.

But in other hand I think it makes plugin code too compilcated. And right now it is too rare case.

I can recommend you to write a linter, which will throw a error if it will find nested rule not in mixin.

**Comment by davidtheclark** [comment]
Do you think it would be better to write a separate linter module to address usage of postcss-nested, or instead to provide an option within postcss-nested that limits its usage and warns of violations?

This is kind of a general question about linter modules (cc/ @MoOx): I was wondering if maybe modules that *extend* CSS syntax (like nested, mixins, extend, etc.) should include *their own* linting options?

**Comment by MoOx** [comment]
I am open to allow custom rules in stylelint (like eslint accepts custom rules from a folder), but I am not open to put non standard stuff into core.

**Comment by ai** [comment]
@davidtheclark I do not want to add a options, because right now mixins code is very simple, because mixin plugins doesn’t know anything about nested. If we will move nested to mixin plugin, it makes code much more compilcate.

But if many users will ask for this is future,  maybe I can add this feature. Right now I think that linter is better solution, because I think it is a rare case.

**Comment by davidtheclark** [comment]
I was thinking of adding the option to *nested*, not to mixin, since it really is about setting a limitation on that plugin, not mixins.

**Comment by ai** [comment]
Nested doesn’t know that it was used only in mixins, because there is no any mixins after `postcss-mixins` run.

**Comment by davidtheclark** [comment]
blergh
