### ISSUE TITLE
Replicating @mixin-content in a functional mixin

### ISSUE THREAD

**Issue by jkimbo** [postcss/postcss-mixins#34]
I've been trying to replicate the functionality of my css mixin as a functional mixin but I can't figure out how to the equivalent of `@mixin-content;` 

```css
@define-mixin respond-to $media {
  @if $media == mobile {
    @media only screen and (max-width: $break-small) { @mixin-content; }
  } @else if $media == tablet {
    @media only screen and (min-width: $break-small-plus) { @mixin-content; }
  } @else if $media == desktop {
    @media only screen and (min-width: $break-large-plus) { @mixin-content; }
  }
}
```

Any help would be really appreciated!

**Comment by ai** [comment]
For this task you should use https://github.com/postcss/postcss-custom-media

Because custom media is W3C standard

**Comment by jkimbo** [comment]
@ai for this specific mixin you're probably right however I think the more general question of how to replicate `@mixin-content` in a functional mixin is still valid.

**Comment by ai** [comment]
Your code looks fine. What exactly goes wrong?

**Comment by jkimbo** [comment]
@ai I was trying to create a functional JS mixin where I could insert the content of the mixin as part of the object being returned, like how `@mixin-content` works in css.

Anyway this question is purely academic now since I solved the issue that caused to me to look into converting the mixin to a functional JS one anyway.

**Comment by ai** [comment]
The `@mixin-content;` should works in this way.

```css
@define-mixin test {
  .test {
    @mixin-content;
  }
}

@test {
  color: black;
}
```

```css
.test {
  color: black;
}
```

**Comment by jkimbo** [comment]
No I'm talking about a JS function mixin like so:

```js
mixins: {
  'test': function() {
    return '.test': {
      // what do I do here??
    }
  }
}
```

**Comment by jkimbo** [comment]
Also I've just realised I've been writing functional when I mean function! Sorry about that.

**Comment by alexlafroscia** [comment]
I'm running into this same issue too... The documentation does not explain how to make a JavaScript mixin that supports `@mixin-content` the way a CSS mixin would.  Unfortunately I need a conditional in my rule, so I can't just use CSS alone.
