### ISSUE TITLE
Conditionals inside a mixin

### ISSUE THREAD

**Issue by Galvo87** [postcss/postcss-mixins#35]
I'm trying to write a simple mixin like this one
```
module.exports = {
	button: function(size) {
		var ciccio = '177px';

		if (size == 'small') {
			ciccio = '99px';
		} else if (size == 'medium') {
			ciccio = '166px'
		} else if (size == 'big') {
			ciccio = '222px'
		}

		return {
			'background-color': 'red',
			'border': '2px solid black',
			'padding': '5px 10px',
			'width': ciccio
		}
	}
}
```
but when I compile postcss through webpack it throws this error...
'CssSyntaxError: Unknown word
			if (size == 'small') {
				return '99px';
    ^
			} else if (size == 'medium') {...

What am I doing wrong? It's not possible to use if statements inside a mixin?

**Comment by TrySound** [comment]
@Galvo87 It's parses like js. Show your build code

**Comment by Galvo87** [comment]
My webpack configuration looks like this...

var lgMixins = require('./app/mixins');

var path = require('path');
var webpack = require('webpack');
var pMixins = require('postcss-mixins')({
	mixins: lgMixins
});
var simpleVars = require('postcss-simple-vars');
var conditionalFor = require('postcss-for');
var conditionalEach = require("postcss-each");
var conditionalIf = require('postcss-conditionals');
var nested = require('postcss-nested');
var customProperties = require("postcss-custom-properties");
var postcssImport = require('postcss-import');
var cssnext = require('cssnext-loader');
var hexToRgba = require('postcss-color-hex-alpha');
var opacityFix = require('postcss-opacity');
var remToPx = require('pixrem');
var mqPacker = require('css-mqpacker');
var zIndex = require('postcss-zindex');
var clearfix = require('postcss-clearfix');
var easings = require('postcss-easings');
var focus = require('postcss-focus');
var cssReport = require('postcss-reporter');
var cssStats = require('postcss-cssstats');
var removeComments = require('postcss-discard-comments');
var fontPath = require('postcss-fontpath');
var browserSync = require('browser-sync-webpack-plugin');

var config = {
	context: __dirname + '/app',
	entry: './index.js',
	output: {
		path: __dirname + '/app',
		filename: 'bundle.js'
	},
	// Setting up plugins
	plugins: [
		new webpack.DefinePlugin({
			ON_TEST: process.env.NODE_ENV === 'test'
		}),
		// BrowserSync options
		new browserSync({
			// Serving to http://localhost:3000
			host: 'localhost',
			port: 3000,
			// proxy the Webpack Dev Server endpoint through BrowserSync
			proxy: 'http://localhost:8080/'
		}, {
			// Should BrowserSync or Webpack Dev Server reload the page?
			reload: true
		})
	],
	// Instructing weboack how to handle different file formats
	module: {
		preloaders: [
			// Linting js with eslint
			{
				test: /\.js$/,
				loader: 'eslint-loader',
				exclude: /node_modules/
			}
		],
		loaders: [
			// Transpiling js with Babel
			{
				test: /\.js$/,
				loader: 'ng-annotate!babel-loader',
				exclude: /node_modules/
			},
			// Extracting html
			{
				test: /\.html$/,
				loader: 'raw-loader',
				exclude: /node_modules/
			},
			// Extracting postcss
			{
				test: /\.css$/,
				loader: 'style-loader!css-loader!cssnext-loader!postcss-loader',
				exclude: /node_modules/
			}
		]
	},
	// Setting up postcss
	postcss: function(webpack) {
		return [
			// Requiring postcss plugins
			postcssImport({
				addDependencyTo: webpack
			}),
			pMixins,
			hexToRgba,
			opacityFix,
			remToPx,
			simpleVars,
			conditionalIf,
			conditionalFor,
			conditionalEach,
			nested,
			customProperties,
			mqPacker,
			zIndex,
			clearfix,
			easings,
			focus,
			removeComments,
			fontPath,
			cssStats(
				function(stats) {
					// console.log(stats);
				}
			)
		]
	},
	// Configuring cssnext options
	cssnext: {
		browsers: [
			'last 4 versions'
		],
		compress: true,
		messages: {
			console: true
		},
		sourcemap: true,
		import: {
			plugins: [
				cssReport
			]
		}
	},
	eslint: {
		configFile: '/.eslintrc'
	}
}

// Building production app in /dist folder
if (process.env.NODE_ENV === 'production') {
	// Setting dist folder path
	config.output.path = __dirname + '/dist';

	// Uglify js files
	config.plugins.push(new webpack.optimize.UglifyJsPlugin({
		compress: {
			warnings: false
		}
	}));

	// Adding sourcemaps
	config.devtool = 'source-map';
}

// Exporting webpack configuration
module.exports = config;

**Comment by TrySound** [comment]
@Galvo87 Which extension has your mixin file?

**Comment by Galvo87** [comment]
var lgMixins = require('./app/mixins');

I have a mixin file with .js extension

**Comment by TrySound** [comment]
Try to remove mixins from postcss and show console.log result of lgMixins

**Comment by Galvo87** [comment]
Logging lgMixins results in:
{ button: [Function] }

Also logging console.log(lgMixins.button('big')); results in:

{ 'background-color': 'red',
  border: '2px solid black',
  padding: '5px 10px',
  width: '222px' }

so I think it's working...

**Comment by Galvo87** [comment]
The issue starts as soon as I put some if loops inside the mixin declaration.

**Comment by ai** [comment]
Can you show a stacktrace of `CssSyntaxError: Unknown word` error? It will contains that strage code, that tries to compile JS to CSS.

**Comment by ai** [comment]
I think problem is not in postcss-mixins, but in some code in other part of app, which tries to `@import 'app/*'`

**Comment by Galvo87** [comment]
Thanks ai, you're right.
I moved the mixin to the main css stylesheet, removed the @import rule and the CssSyntaxError: Unknown word is gone, but now it seems that the if loop is being ignored, the var ciccio is always equal to '177px'...
But how can I get this to work with postcss-import plugin?

**Comment by ai** [comment]
Sorry, I didn’t use `postcss-import` :). I think with webpack you should have one dependencies tree. If you require one component into other, it should automatially get JS and CSS.

**Comment by Galvo87** [comment]
Ok, I'm just starting out with Webpack... so you mean that I shouldn't use postcss-import?
