### ISSUE TITLE
Can't use CSS variable

### ISSUE THREAD

**Issue by rdierckx** [postcss/postcss-mixins#4]
I can't put a CSS variable in my mixin parameter. Here an exemple:
` @mixin ui-element-size var(--ui-default-height) var(--r-gutter-x) 0.875rem;`
will generate that:
` line-height: var(--ui-default-height);`

**Comment by ai** [comment]
What PostCSS plugins list do you use?

**Comment by rdierckx** [comment]
I'm using Cssnext. I can fix this issue by doubling my variable like this `$r-gutter-x : var(--r-gutter-x)` but it's not very convenient :/.

**Comment by ai** [comment]
It is not about variable syntax :-). Do you have cssnext before or after postcss-simple-vars?
