### ISSUE TITLE
Undefined mixin on first run

### ISSUE THREAD

**Issue by stephenway** [postcss/postcss-mixins#46]
With mixins I'm importing from `node_modules`

```css
@import 'stylep-dropdown';

.c-dropcard--right {
  @mixin dropdown-callout-inline;
  @mixin dropdown-inline .5em 1em, 0, 289px;
  @mixin dropdown-solid var(--callout-bg-color), var(--grey-100), rgba(0, 0, 0, .75), 4px, var(--grey-600) 0 0 7px;
  @mixin dropdown-callout-solid var(--callout-bg-color), 0 0 3px 1px rgba(0, 0, 0, .4);
  @mixin dropdown-callout-left-top;
}
```

I'm getting an error:
```shell
[09:40:35] Starting 'css'...

events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: postcss-mixins: /Users/Stephen/project/src/patterns/dropcard.css:17:3: Undefined mixin dropdown-callout-inline
.c-dropcard--right {
  @mixin dropdown-callout-inline;
  ^
  @mixin dropdown-inline .5em 1em, 0, 289px;
```
And with the same code on second run
```shell
[09:45:08] Starting 'css'...
[09:45:11] Finished 'css' after 2.88 s
```

It's seeming like there is a open loop where it can't read or refresh what's in `node_modules` on first run.

**Comment by ai** [comment]
Where did you define mixins?

And what is your plugin list?

**Comment by ai** [comment]
Maybe this issue is related? https://github.com/postcss/postcss-import/issues/168

**Comment by stephenway** [comment]
Mixins here, installed via NPM https://github.com/stylep/stylep-dropdown/blob/master/index.css

and my processors are:
![screen shot 2016-02-08 at 2 41 17 pm](https://cloud.githubusercontent.com/assets/38894/12901737/0e9bd1fc-ce72-11e5-8063-c920af656661.png)

**Comment by ai** [comment]
Yeap, looks like you have problem with import.

You can always check it by open mix in plugin JS file and put `console.log(css.toString())` inside.

@ben-ben-eb maybe we should add some option for postcss-devtools to see input CSS for some plugin?

**Comment by stephenway** [comment]
@ben-eb

**Comment by ben-eb** [comment]
Sure, PR welcome.

**Comment by toomuchdesign** [comment]
In my case, switching back to postcss-import v.7 fixed the problem. [Related issue](https://github.com/postcss/postcss-import/issues/211).

**Comment by stephenway** [comment]
Yea, or in my case, switched to [postcss-apply](https://github.com/pascalduez/postcss-apply).
