### ISSUE TITLE
How to use mixinsDir with arguments

### ISSUE THREAD

**Issue by timkelty** [postcss/postcss-mixins#5]
I'm trying to autoload from `mixinsDir`. Is it possible to pass arguments to my mixins this way?

**Comment by ai** [comment]
Yes.

```js
module.exports = function (size) {
    return {
        width: size,
        height: size
    },
}
```

```css
a {
  @mixin size 10px;
}
```

**Comment by timkelty** [comment]
For this to work, I had to pass `mixin` as the first arg and everything after were the passed arguments. That seem right?

```
module.exports = function (mixin, size) {
    return {
        width: size,
        height: size
    },
}
```

**Comment by ai** [comment]
@timkelty ouh, yes. I forgot about `mixin` node argument :)
