### ISSUE TITLE
Defining default values for mixins defined in JS file

### ISSUE THREAD

**Issue by benfrain** [postcss/postcss-mixins#50]
Sorry; this is likely due to my lack of understanding. I have a mixin defined in a JS file — it takes a couple of arguments so I am attempting to define it like this:

````
MakeSpinner: function ($backgroundColor, $highlightColor)  {
        return {
            "content": "''",
            "border": "'2px solid ' + $backgroundColor",
            "border-left-color": $highlightColor,
            "border-radius": "999px",
            "opacity": "0"
        };
    }
````

However, I get the error `Undefined variable $backgroundColor`which makes some sense as this is an argument rather than an actual variable. 

How should I be writing this?

**Comment by ai** [comment]
Seems like you have a JS syntax error. Here is a correct source:

```js
MakeSpinner: function ($backgroundColor, $highlightColor)  {
        return {
            "content": "''",
            "border": '2px solid ' + $backgroundColor,
            "border-left-color": $highlightColor,
            "border-radius": "999px",
            "opacity": "0"
        };
    }
```

**Comment by ai** [comment]
Also you can define this type of mixins in CSS. For me opinion CSS is better for this type of mixins.

**Comment by benfrain** [comment]
Thanks @ai - doing it in JS rather than CSS was more to do with making the mixins available easily to multiple CSS files without needing to `@import` each time.

I'm afraid when I use that mixin like this:

````scss
.selector {
    &:after {
        @mixin MakeSpinner $color-green, $color-green-special;
    }
}
````

It yields this output:

````css
.selector:after {
    content: '';
    border: 2px solid @mixin MakeSpinner #14805e, #4acfa5;
    border-left-color: #14805e;
    border-radius: 999px;
    opacity: 0;
}
````

Is this a bug?

**Comment by ai** [comment]
@benfrain JS mixins accepts a `rule` in first argument (I forget it too :) ). Here is a fixed version:

```js
MakeSpinner: function (rule, $backgroundColor, $highlightColor)  {
        return {
            "content": "''",
            "border": '2px solid ' + $backgroundColor,
            "border-left-color": $highlightColor,
            "border-radius": "999px",
            "opacity": "0"
        };
    }
```

**Comment by benfrain** [comment]
WooT!!!!

Brilliant, thanks @ai — all sorted now!

**Comment by benfrain** [comment]
Would you like me to add some info on this in the readme and provide a PR?

**Comment by ai** [comment]
@benfrain definitely! :)
