### ISSUE TITLE
Media queries in mixins or mixins in media queries

### ISSUE THREAD

**Issue by akhost** [postcss/postcss-mixins#53]
I am using `v4.0.1` and am having nested at-rule issues. I see that others have posted similar issues that were resolved by upgrading to `v4.0.1`, however this has not fixed my issue.

I have tried adding media queries to my mixin:
`@define-mixin myMixin{`
    `foo: bar;`
    `@media (min-width: 480px ){`
        `foo: bar;`
    `}`
`}`
and also tried adding my mixin inside my media query:
`.myClass{`
    `@mixin myMixin;`
    `@media (min-width: 480px ){`
        `@mixin myMixin;`
    `}`
`}`

In both cases, I am getting the following error:
> Defining at-rules cannot contain statements

And the CSS in the media query is ignored (but it compiles).

Here is a list of my dependencies:
`"dependencies": {`
    `"autoprefixer": "^6.3.1",`
    `"babel-preset-es2015": "^6.3.13",`
    `"babel-preset-react": "^6.3.13",`
    `"bower": "^1.7.2",`
    `"gulp": "^3.9.0",`
    `"gulp-autoprefixer": "^3.1.0",`
    `"gulp-cssnano": "^2.0.0",`
    `"gulp-imagemin": "^2.4.0",`
    `"gulp-postcss": "^6.0.1",`
    `"imagemin-pngquant": "^4.2.0",`
    `"laravel-elixir": "^5.0.0",`
    `"pixrem": "^3.0.0",`
    `"postcss-conditionals": "^2.0.0",`
    `"postcss-each": "^0.9.1",`
    `"postcss-import": "^7.1.3",`
    `"postcss-math": "0.0.1",`
    `"postcss-mixins": "^4.0.1",`
    `"postcss-nested": "^1.0.0",`
    `"postcss-reporter": "^1.3.0",`
    `"postcss-scss": "^0.1.3",`
    `"postcss-simple-extend": "^1.0.0",`
    `"postcss-simple-vars": "^1.1.0",`
    `"precss": "^1.3.0",`
    `"yargs": "^4.4.0"`
  `}`

Any thoughts? Thank you.

**Comment by ai** [comment]
Show you input CSS and output (some very small example), I will try to implement.

**Comment by akhost** [comment]
I just went to create a simple example and now it is working. Apparently the `npm install` change to upgrade from v2.1.1 to v4.0.1 had not taken effect. Sorry about that and thanks so much for the quick reply!

**Comment by akhost** [comment]
@ai, I finally figured out the problem, which is still an issue in `v4.0.1`. Placing a mixin inside a `@define-placeholder` ([the simple-extend plugin](https://github.com/davidtheclark/postcss-simple-extend)) causes the "Defining at-rules cannot contain statements" error. I have resolved this for now by simply not using the simple-extends with mixins, but if you find a solution (or want an example), please let me know. Thanks!

**Comment by ai** [comment]
Yeap, using a extend with mixins is not a good idea ;).

Honestly, there is no real sense to use `extend` when you have gzip ;).

**Comment by ai** [comment]
If you want to fix it, you should create issue in postcss-simple-extend, because I had not use it and it will be hard to me to find problem.
