### ISSUE TITLE
How to use mixin inside mixin?

### ISSUE THREAD

**Issue by asifshirazi** [postcss/postcss-mixins#55]
Need help!
I'm trying to translate my scss recursion mixin, you can see my scss pen [here](http://codepen.io/shirazi/pen/qZzYjv/) .

I'm using [PreCSS](https://github.com/jonathantneal/precss) and here is my Postcss code:

    $treeLevels: 20;
    $treeIndentation: 6px;

    @define-mixin treeItem $i{
        li{
            @if $i != 0{
                > .angular-ui-tree-handle{ padding-left: calc($treeIndentation * ($treeLevels - $i + 2));}
                @mixin treeItem calc($i - 1);
            }
        }
    }
    ul{ @mixin treeItem $treeLevels; }

and my result is:

    ul li > .angular-ui-tree-handle { padding-left:12px;}
    ul li li { @mixin treeItem calc(calc($treeLevels - 1) - 1);}
    ul li li > .angular-ui-tree-handle { padding-left:18px;}

**Comment by ai** [comment]
What version of postcss-mixins do you use? I specially added code for nested mixin support :)
https://github.com/postcss/postcss-mixins/blob/master/CHANGELOG.md#30

**Comment by asifshirazi** [comment]
Thanks for quick reply! :)
PreCSS is using v2.1.0, I've to inform him.
[https://github.com/jonathantneal/precss/blob/master/package.json](https://github.com/jonathantneal/precss/blob/master/package.json)
