### ISSUE TITLE
Define at-rules inside at-rules?

### ISSUE THREAD

**Issue by RyoIkarashi** [postcss/postcss-mixins#57]
When I define at-rules inside at-rules, I get an error saying `Defining at-rules cannot contain statements`

The code that throws an error is something like below.
```css
@define-mixin headings $from: 1, $to: 6 {
  @if $from >= 1 and $to <= 6 {
    @for $i from $from to $to {
      h$i {
        @extend base-heading;
      }
    }
  }
  @define-placeholder base-heading {
    @mixin-content;
  }
}
```

Any support or plan for solving this?

**Comment by ai** [comment]
Could you show full stack trace. I didn't remember this error from my plugin.

**Comment by ai** [comment]
But your mixin is very complicated. PostCSS idea is to avoid programming code from CSS. CSS should be declarative.

Why you could not write just:

```css
h1, h2, h3, h4, h5, h6 {
  color: black;
}
```

It will be a much simpler and readable than this magic mixin 😉
