### ISSUE TITLE
@mixin-content in JS mixin functions?

### ISSUE THREAD

**Issue by channikhabra** [postcss/postcss-mixins#58]
Is there any way to access the @mixin-content when defining mixins as js functions? It seems the first argument include complete source of the file which uses the mixin.

**Comment by ai** [comment]
Function accepts `atRule` object as first argument. You can take `mixin-content` body from it:

```js
function (atRule, ...args) {
  let rule = postcss.rule({ selector: 'a' })
  atRule.insertAfter(rule)
  rule.append(atRule.nodes)
}
```

**Comment by ai** [comment]
Hm, maybe I should add it to docs

**Comment by ai** [comment]
I added docs d92e4b0
