### ISSUE TITLE
SugarSS syntax support for global mixins

### ISSUE THREAD

**Issue by akella** [postcss/postcss-mixins#59]
Right now plugin does not support .sss files for mixins
What i do:
```js
require('postcss-mixins')({
        mixinsDir: path.join(__dirname, 'mixins')
    }),
```
In that dir i have size.sss file:
```sass
@define-mixin size $size
	width: $size
	height: $size
```
What happens: mixin does not work, throws error on processing.
Expected that to work.

**Comment by ai** [comment]
Sure, I will fix it in airplane tonight

**Comment by ai** [comment]
Done 13bbd9d

**Comment by ai** [comment]
Release in 5.1
