### ISSUE TITLE
Synchronous version

### ISSUE THREAD

**Issue by plusbpm** [postcss/postcss-mixins#60]
Is it possible to create a synchronous version for use with the require hook? Or add the appropriate option?

**Comment by ai** [comment]
Could you example what is “require hook” and why you need synchronous version?

**Comment by plusbpm** [comment]
Non-working example of using the plug-in as part of precss:
```
  var hook = require( "css-modules-require-hook" );
  var precss = require( "precss" );

  hook({
    prepend: [precss()],
    extensions: [".css"],
    generateScopedName: "[path]-[local]"
  });
```
But about working with disabled the import and mixins:
```
  var hook = require( "css-modules-require-hook" );
  var precss = require( "precss" );

  hook({
    prepend: [precss({
      import: { disable: true },
      mixins: { disable: true }
    })],
    extensions: [".css"],
    generateScopedName: "[path]-[local]"
  });
```
Module css-modules-require-hook only requires synchronous plug-ins.
Require hook is needed to convert the CSS on the fly

**Comment by ai** [comment]
Fixed 78257fa

**Comment by ai** [comment]
Release in 5.3

**Comment by plusbpm** [comment]
Thank you!
