### ISSUE TITLE
Struggling to create a dynamic mixin

### ISSUE THREAD

**Issue by rvetere** [postcss/postcss-mixins#64]
Hi folks,

first, thanks for the wonderful plugin and your work! i'm struggling to create a dynamic gradient mixin. My first attempt to solve a basic `linear-gradient` was a .pcss file like this:

```
@define-mixin gradientVertical $colorA, $stopA, $colorB, $stopB {
  background: -moz-linear-gradient(top, $(colorA) $(stopA), $(colorB) $(stopB)); /* FF3.6-15 */
  background: -webkit-linear-gradient(top, $(colorA) $(stopA), $(colorB) $(stopB)); /* Chrome10-25,Safari5.1-6 */
  background: linear-gradient(to bottom, $(colorA) $(stopA), $(colorB) $(stopB));
}
```

it's working, yay! but the downside is the explicit calling of every single variable in there.

what if i just want to add an additional color-stop? i'll have to create another mixin... this can't be the solution i thought and so i started to try it with a javascript mixin:

https://gist.github.com/rvetere/8069ef1f6836f94f79141038d8c0b7b0

this is my attempt so far - it is working! well, not completely finished yet - but the case i am testing right now will come out with the correct output of a working linear-gradient.

The problem remaining and why i want to ask here - how can we handle the case where we need to output several variants of the same property?

I'm showing this in the return of my gist - it was my obvious bad attempt to generate multiple `background-image` definitions for the several browser implementations.

but clearly as javascript works - i'm duplicating the key's this way in my object, actually overriding the previous value it got and so the outcoming object will only contain 1 single `background-image` in the end -> the last one that was defined which has won.

i can see this in my outcoming css - only one survives the game... 

do you guys know any workaround in such a mixin to solve this case?

**Comment by ai** [comment]
First, you don’t this mixin. You should use only Autoprefixer for prefixes. So you need just:

```css
background: linear-gradient(to bottom, $(colorA) $(stopA), $(colorB) $(stopB));
```

In this case mixin is not really useful.

**Comment by ai** [comment]
Answer for you main question: use “function” mixins. It is pure JS function and you can access to `arguments` list.

https://github.com/postcss/postcss-mixins#function-mixin

**Comment by rvetere** [comment]
very cool - thanks for your replies 😉
