### ISSUE TITLE
`Undefined mixin` when sassdoc `///` comment on top of `@define-mixin` block

### ISSUE THREAD

**Issue by lkraav** [postcss/postcss-mixins#66]
5.4.1
 
Example:
```scss
/// @since 2017.01.22
@define-mixin whatever $position: before {
    ...
}
```

Having comments on top of `@define-mixin` seems to make the engine skip the whole mixin, which will result in `Undefined mixin` later. Your thoughts?

**Comment by ai** [comment]
`//` comments are prohibited in CSS syntax. Did you use [`postcss-scss`](https://github.com/postcss/postcss-scss) to parse this comments?

**Comment by lkraav** [comment]
> // comments are prohibited in CSS syntax. Did you use postcss-scss to parse this comments?

Thanks. Ouch, I did not think of this.

That brings me to the next (post-close) question... what's the appropriate current CSS docblock standard then?

**Comment by ai** [comment]
Sorry, I don't use docblocks in my CSS and don't know the best option. Try mdcss.
