### ISSUE TITLE
Option to normalize args

### ISSUE THREAD

**Issue by timkelty** [postcss/postcss-mixins#7]
It would be nice if there were an option to normalize args, e.g. `'true'`/`'false'` strings to booleans, and numbers to numbers instead of strings.

**Comment by timkelty** [comment]
Use case:
```
module.exports = function(mixin, on) {
  var props = {};
  on = on || true;

  // All mixin args are passed as strings
  on = on && on !== 'false';

  if (on) {
    props['-webkit-font-smoothing'] = 'antialiased';
    props['-moz-osx-font-smoothing'] = 'grayscale';
  } else {
    props['-webkit-font-smoothing'] = 'subpixel-antialiased';
    props['-moz-osx-font-smoothing'] = 'auto';
  }

  return props;
};
```

**Comment by ai** [comment]
PostCSS mixins are used as simple templates, not as s a some complicated logic functions, like in Sass mixins.

What is your user case?

**Comment by timkelty** [comment]
Use case https://github.com/postcss/postcss-mixins/issues/7#issuecomment-95338867

**Comment by ai** [comment]
There is no `false`/`true` words in any CSS spec. So I think you should use more CSS API.

**Comment by ai** [comment]
In this case two different mixins is a better solution.

**Comment by timkelty** [comment]
Ok, thanks.
