### ISSUE TITLE
Sync API

### ISSUE THREAD

**Issue by adierkens** [postcss/postcss-mixins#73]
I'm trying to use the [babel-plugin-css-modules-transform](https://github.com/michalkvasnicak/babel-plugin-css-modules-transform) babel-plugin in conjunction with postcss to get my css working with a module build w/o having to use webpack.

Babel transforms need to be synchronous, so all of my postcss plugins also need to be. Is there a sync version of the `postcss-mixins` plugin?

**Comment by ai** [comment]
If you don’t set any files, `postcss-mixins` will be sync https://github.com/postcss/postcss-mixins/blob/master/index.js#L161

Is it OK for you?

**Comment by adierkens** [comment]
@ai Gotcha, Thanks!
