### ISSUE TITLE
Switch to css variables instead of sass like variables

### ISSUE THREAD

**Issue by equinusocio** [postcss/postcss-mixins#75]
It would be awesome write vars with the native css syntax instead of sass. 
1. It avoid conflicts with sass or other plugins
2. It avoid confusion between sass/postcss
3. Postcss is a postprocessor, so starting syntax should be more css like

The related plugin is https://github.com/MadLittleMods/postcss-css-variables

**Comment by ai** [comment]
But mixins is not-standard syntax. For my opinion it will be strange 😊.

But if you like it, fork the project and create your own plugin. It is easy.

**Comment by equinusocio** [comment]
is not about a "standard". Is about confusing and conflicts.

**Comment by ai** [comment]
Anyway you will have conflict with `@mixin` at-rule.

You can try `@apply` from cssnext.
