### ISSUE TITLE
Plugin causes webpack watch to stop when it throws "Undefined mixin" error

### ISSUE THREAD

**Issue by cihadturhan** [postcss/postcss-mixins#77]
If you type name of the mixin incorrectly, e.g.
```css
@mixin imagePlaceholde; /*<-- let's say we forgot "r" */
```
this causes webpack watcher to stop. You have to restart webpack dev server and sometimes this could be frustrating. I tried `{silent: true}` but it doesn't show any error so that is not a solution.

Is there any solution?

**Comment by ai** [comment]
@cihadturhan you should send issue to `postcss-loader`. It is related to all PostCSS plugins not only this one.

**Comment by cihadturhan** [comment]
@ai will do. Thanks for quick reply.
