### ISSUE TITLE
Sass @content feature support?

### ISSUE THREAD

**Issue by MadLittleMods** [postcss/postcss-mixins#8]
In Sass you are able to pass in arbitrary content into a mixin with the `@content` directive. 

Is there a way to accomplish this now? Plans to support it?

```
$should-show: true;

@mixin some-mixin {
	@if $should-show {
		@content;
	}
}

.item {
	width: 100px;
	height: 100px;

	background: rgba(255, 0, 0, 1);

	@include some-mixin {
		background: rgba(0, 255, 0, 1);
	}
}
```

What about [passing arguments from a mixin to a content block](https://github.com/sass/sass/issues/871)? 

[*via jackmahoney's comment*](https://github.com/sass/sass/issues/871#issuecomment-38344615)
```
@mixin foo($a, $b){
    @content($c, $d)
}

@include foo($a, $b) using($c, $d) {
    // ...
}
```

**Comment by ai** [comment]
Yeap, I will add it when i finish PostCSS Plugins Guidelines.

**Comment by ai** [comment]
Done c6773d5
