### ISSUE TITLE
Error: a term expected

### ISSUE THREAD

**Issue by budarin** [postcss/postcss-mixins#83]
Hi!
have a WebStorm project with postCSS & plugins.
postCSS config:
```js
const path = require('path');

const env = process.env.NODE_ENV;
const plugins = [
    require('postcss-cssnext')({
        // browsers: ['Chrome >= 64', 'Firefox >= 58', 'Safari >= 11', 'iOS >= 10.13', 'Edge >= 41'],
        features: {
            autoprefixer: true,
        },
        cascade: false,
    }),
    require('postcss-utilities')({
        ie8: false,
        centerMethod: 'flexbox',
    }),
    require('postcss-mixins')({
        mixinsDir: path.resolve('./src/common/assets/css/mixins'),
    }),
];

if (env === 'production') {
    plugins.push(require('cssnano'));
}

module.exports = {
    plugins: plugins,
};
```

and have a mixin in size.pcss:
```css
@define-mixin size $size {
    width: $size;
    height: $size;
}
```
project compiles successfully but there is an error in code before symbol $ - Error: a term expected.

can you help me what the error is about, please!
```

**Comment by ai** [comment]
1. Try to move `postcss-mixins` as the first plugin PostCSS config
2. If it will not fix the problem, show me full error. It should be a plugin name there.

**Comment by budarin** [comment]
have moved postcss-mixins at the first place but there is no effect:

![default](https://user-images.githubusercontent.com/8055157/35639325-ea1854e8-06ca-11e8-9442-e4646acf988d.png)

Full text of the error: Error:(2, 11) a term expected

**Comment by ai** [comment]
Where do you see this error? On console or in IDE?

**Comment by budarin** [comment]
there is no error in console while compiling - there is the error in IDE

**Comment by budarin** [comment]
I see - the error is a problem IDE not the plugin, sorry!
