### ISSUE TITLE
More syntax options?

### ISSUE THREAD

**Issue by hmalaud** [postcss/postcss-mixins#91]
In CSS, @ are used for existing pieces of code, such as @media, thus making it confusing to use @ when not using plain CSS language in a PostCSS file. This is one of the reasons I left Scss for Stylus. Would it be possible to change the @define-mixin in a more agnostic syntax like Sass' (example below) and have parenthesis wrapping parameters?

```
=transform($property)
  -webkit-transform: $property
  -ms-transform:     $property
  transform:         $property

.box
  +transform(rotate(30deg))
```

**Comment by ai** [comment]
it is possible, but much harder, than you think.

You need to create a custom syntax (or to send PR in [`sugarss`](https://github.com/postcss/sugarss)) to parse `+transform(30deg)` as `@mixin transform(30deg)`.

It is hard and I try to be focused on a different thing, so I do not want to do it. But I will be open for PR and could help you if you want to write it.
