### ISSUE TITLE
Sync API

### ISSUE THREAD

**Issue by hipstersmoothie** [postcss/postcss-mixins#95]
It would be super useful to run this plugin in sync mode. many editor related plugins choke on async plugins

**Comment by hipstersmoothie** [comment]
I have tried doing this myself and it was quite a bit of change. How about a new option to just pass in your mixins as a string?

**Comment by ai** [comment]
I don't think we have in API in Node.js to run async function as sync function. Without this API I just don't know how to do it in the core. You may ask plugin developers to add some option to force sync, but it will be too hard to rewrite all plugins.

If we have it, I will re-open the issue.
